#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1)
echo "set INSTDIR $INSTDIR"

chmod 644 $INSTDIR/usr/local/share/titan/plugins/kravencfg/*
chmod 755 $INSTDIR/usr/local/share/titan/plugins/kravencfg/kravencfg.sh

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-tools-kravencfg --dest $1
fi

exit 0
