#!/bin/sh
INSTDIR="$1" 
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/sispmctl"

rm -r "$PLUGINDIR" >/dev/null 2>&1
rm /mnt/plugin/ps01sispm 
rm /mnt/plugin/pe01sispm 

if [ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ];then
	opkg remove titan-plugin-tools-sispmctl --dest $1
fi

exit 0
