#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1)
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/sispmctl"

if [ -e "$PLUGINDIR/sispmctl.conf" ]; then
	cp "$PLUGINDIR/sispmctl.conf" /tmp/sispmctl.conf 
	cp "$PLUGINDIR/bin/g1_script.sh" /tmp/g1_script.sh >/dev/null 2>&1
	cp "$PLUGINDIR/bin/g2_script.sh" /tmp/g2_script.sh >/dev/null 2>&1
	cp "$PLUGINDIR/bin/g3_script.sh" /tmp/g3_script.sh >/dev/null 2>&1
	cp "$PLUGINDIR/bin/g4_script.sh" /tmp/g4_script.sh >/dev/null 2>&1
fi

rm -rf "$PLUGINDIR"

exit 0