#!/bin/sh
TMP=/tmp/.tmp

PLUGINDIR=/var/usr/local/share/titan/plugins/networkbrowser
rm -r /var/usr/local/share/titan/plugins/networkbrowser

echo "successfully removed"
if [ `df | grep /dev/mtdblock | grep var | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1 | wc -l` -eq 1 ]; then
	SPACE=`df | grep /dev/mtdblock | grep var | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1`
	FREE=`expr $SPACE - 100`
	echo new freespace size $FREE kb
else
	echo "syncing disk"
	sync
fi
exit 0