#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0


if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-gui-e2starter --dest $1
	e2.sh remove
fi

exit 0
