#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-player-gmediarender --dest $1
	opkg install titan-gmediarender
else
	INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1);fi
echo "set INSTDIR $INSTDIR"
	PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/gmediarender"

	sed s#_path_#"$INSTDIR"#g -i "$PLUGINDIR/run"

	if [ "/var" != "$INSTDIR" ]; then
		rm -rf /var/usr/lib/gstreamer-0.10
		ln -s "$INSTDIR/lib/gstreamer-0.10" /var/usr/lib
	fi
fi

exit 0
