#!/bin/sh

echo "Dest: $1"
echo "Script: $0"

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-player-gmediarender --dest $1
	opkg install titan-gmediarender
fi

if [ -e /etc/.ddtbuild ];then
	INSTDIR="$1"
	PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/player/gmediarender"

	if [ "/var" != "$INSTDIR" ]; then
		rm -rf /var/usr/lib/gstreamer-0.10
		ln -s "$INSTDIR/lib/gstreamer-0.10" /var/usr/lib
	fi
fi

if [ "$1" != "upgrade" ] && [ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ];then
	if [ "root" != "$1" ]; then
		rm -rf /usr/share/gmediarender
		ln -s "$1/usr/share/gmediarender" /usr/share/gmediarender
	fi
fi

exit 0
