#!/bin/sh

echo "Dest: $1"
echo "Script: $0"

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-player-gmediarender --dest $1
	opkg remove titan-gmediarender
elif [ "$1" != "upgrade" ] && [ ! -e /etc/.oebuild ] && [ ! -e /etc/.ovbuild ];then
	INSTDIR="$1"
	PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/player/gmediarender"

	rm -rf "$PLUGINDIR" >/dev/null 2>&1

	if [ "/var" != "$INSTDIR" ]; then
		rm -rf /var/usr/lib/gstreamer-0.10
	fi
fi

exit 0
