#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-player-gmediarender --dest $1
	opkg remove titan-gmediarender
else
	INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1)
echo "set INSTDIR $INSTDIR"
	PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/gmediarender"

	rm -rf "$PLUGINDIR" >/dev/null 2>&1

	if [ "/var" != "$INSTDIR" ]; then
		rm -rf /var/usr/lib/gstreamer-0.10
	fi
fi

exit 0
