#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1);fi
echo "set INSTDIR $INSTDIR"

echo prerm INSTDIR $INSTDIR

if [ ! -e "$INSTDIR/etc/minidlna.conf.minidlna" ]; then
	echo "remove tpk minidlna.conf"
	rm -f "$INSTDIR/etc/minidlna.conf"
fi

exit 0
