#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1);fi
echo "set INSTDIR $INSTDIR"

if [ "$INSTDIR" == "/var" ]; then
	rm -rf "$INSTDIR/usr/local/share/titan/skin/default"
fi

exit 0
