#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1)
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/sispmctl"

rm -r "$PLUGINDIR" >/dev/null 2>&1
rm /mnt/plugin/ps01sispm 
rm /mnt/plugin/pe01sispm 

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-tools-sispmctl --dest $1
fi

exit 0
