#!/bin/sh

echo "Dest: $1"
echo "Script: $0"

INSTDIR="$1"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/network/xupnpd"

rm -rf "$PLUGINDIR" >/dev/null 2>&1
rm -rf $INSTDIR/etc/xupnpd >/dev/null 2>&1

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-network-xupnpd --dest $1
fi

exit 0
