#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1)
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/xupnpd"
export XUPNPDROOTDIR=$INSTDIR/etc/xupnpd
echo INSTDIR $INSTDIR
echo PLUGINDIR $PLUGINDIR
mkdir $INSTDIR/etc/xupnpd/config

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-network-xupnpd --dest $1
fi

exit 0
