#!/bin/sh

echo "Dest: $1"
echo "Script: $0"

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-network-xupnpd --dest $1
fi

if [ "$1" != "upgrade" ];then
	INSTDIR="$1"
	PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/network/xupnpd"
	export XUPNPDROOTDIR=$INSTDIR/etc/xupnpd
	echo INSTDIR $INSTDIR
	echo PLUGINDIR $PLUGINDIR
	mkdir -p $INSTDIR/etc/xupnpd/config
fi

exit 0
