#!/bin/sh

echo "Dest: $1"
echo "Script: $0"
#rm -rf /var/etc/lcd4linux.conf

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-tools-lcdpearl1 --dest $1
fi

exit 0
