#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1);fi
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/lcdpearl1" 

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-tools-lcdpearl1 --dest $1
fi

exit 0
