#!/bin/sh
INSTDIR="$1"  
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/lcdpearl1" 

rm -rf "$PLUGINDIR" >/dev/null 2>&1
rm -rf /var/etc/lcd4linux.conf

if [ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ];then
	opkg remove titan-plugin-tools-lcdpearl1 --dest $1
fi

exit 0
