#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0


if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-tools-instar --dest $1
fi

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1)
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/instar"

if [ -e /tmp/instar.conf ]; then
	mv "$PLUGINDIR/instar.conf" "$PLUGINDIR/instar.conf_org"
	cp /tmp/instar.conf "$PLUGINDIR/instar.conf"
	rm /tmp/instar.conf
fi

exit 0
