#!/bin/sh

echo "Dest: $1"
echo "Script: $0"


if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-browser-netsurf --dest $1
	opkg install titan-netsurf
fi

exit 0
