#!/bin/sh
INSTDIR="$1"  
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/multiimage"

rm -rf "$PLUGINDIR" >/dev/null 2>&1

if [ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ];then
	opkg remove titan-plugin-tools-multiimage --dest $1
fi

exit 0
