LIB = netlib.a

OBJS = list.o nbtscan.o range.o showmount.o smbinfo.o statusq.o

DEPS = $(patsubst %.o,%.d,$(OBJS))

CC = gcc
AR = ar

CFLAGS = -Os -Wall -g -I.

all: $(LIB)

$(LIB): $(OBJS) Makefile
	$(AR) ru  $@ $(OBJS)
	ranlib $@

%.o: %.c
	$(CC) -MD $(CFLAGS) -c $<

clean:
	rm $(OBJS) $(DEPS) $(LIB)


-include $(DEPS)
