#!/bin/sh
INSTDIR="$1"

chmod 644 $INSTDIR/usr/local/share/titan/plugins/kravencfg/*
chmod 755 $INSTDIR/usr/local/share/titan/plugins/kravencfg/kravencfg.sh

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-tools-kravencfg --dest $1
fi

exit 0
