#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0


if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-tools-stopifnotused --dest $1
fi

exit 0
