#!/bin/sh
INSTDIR="$1"

sed s#_path_#"$INSTDIR"#g -i "$INSTDIR/usr/local/share/titan/skin/MegaStyle-Grey/skinconfig"
sed s#_path_#"$INSTDIR"#g -i "$INSTDIR/usr/local/share/titan/skin/MegaStyle-Grey/skinconfig.default"

exit 0
