#!/bin/sh
SVNUSER=$1
SVNPASS=$2
SVNURL=$3

if [ $# -ne 3 ]; then
	echo "|---------------------------------------------------------------------------------------------|"
	echo "|                                                                                             |"
	echo "| Parser Make Script                                                                          |"
	echo "|                                                                                             |"
	echo '| use ./make-parser <svnuser> <svnpass> <svnurl>                                                 |'
	echo "|                                                                                             |"
	echo "| for svnuser <your>                                                                          |"
	echo "| for svnpass <your>                                                                          |"
	echo "| for svnurl <your>                                                                           |"
	echo "|                                                                                             |"
	echo "|---------------------------------------------------------------------------------------------|"
	echo "|                                                                            v2.1@dev-team    |"
	echo "|---------------------------------------------------------------------------------------------|"
	exit 1
fi

HOMEDIR=`pwd`
TMP=.tmp

rm -rf "$HOME"/parser/BUILD
mkdir -p "$HOME"/parser/BUILD
cd "$HOME"/parser/BUILD

svn co --username $SVNUSER --password $SVNPASS http://sbnc.myphotos.cc/svn/titan/titan/tools/tithekmainmenu "$HOME"/parser/BUILD/mediathek
svn co --username $SVNUSER --password $SVNPASS http://sbnc.myphotos.cc/svn/titan/skins/tithek/menu "$HOME"/parser/BUILD/mediathek/menu

rm -rf `find "$HOME"/parser/BUILD/mediathek -type d -name "*.svn"`

rm -rf /var/www/atemio/web/mediathek/menu
rm -rf /var/www/atemio/web/mediathek/*.list
mv -f "$HOME"/parser/BUILD/mediathek/* /var/www/atemio/web/mediathek
mv -f "$HOME"/parser/*.sh "$HOME"/parser/BUILD

lasttimestamp=`cat /var/www/atemio/web/mediathek/lasttimestamp`
lasttimestamp=`expr $lasttimestamp + 84500`
today=`date +%s`

echo today $today
echo lasttimestamp $lasttimestamp

if [ $today -gt $lasttimestamp ];then
	ls -1 "$HOME"/parser/BUILD/*.sh | sort -r > tmp.txt
else
	echo else
	ls -1 "$HOME"/parser/BUILD/*.sh | grep -v beeg.sh | grep -v kinox.sh | sort -r > "$HOME"/parser/BUILD/tmp.txt
fi

LINE=`cat "$HOME"/parser/BUILD/tmp.txt`
echo LINE $LINE
for TYPE in $LINE; do
	if [ $TYPE == "beeg.sh" ] || [ $TYPE == "kinox.sh" ];then
		echo `date +%s` >/var/www/atemio/web/mediathek/lasttimestamp
	fi

	$TYPE
	echo "[make-parser] make $TYPE"
	STARTTIME=`date +"%Y.%m.%d_%H.%M.%S"`
done

cd "$HOME"/parser/BUILD/_full
LINE=`ls -1`
TIME=`date +"%Y.%m.%d_%H.%M.%S"`

for TYPE in $LINE; do
	mv $TYPE /var/www/atemio/web/mediathek/"$TYPE"_"$TIME"
	echo "[make-parser]" mv "$TYPE" "> /var/www/atemio/web/mediathek/""$TYPE"_"$TIME"
	rm -rf /var/www/atemio/web/mediathek/"$TYPE"
	echo "[make-parser]" ln -s "$TYPE"_"$TIME" /var/www/atemio/web/mediathek/"$TYPE"
	ln -s "$TYPE"_"$TIME" /var/www/atemio/web/mediathek/"$TYPE"

	BSLIST=`ls -1 /var/www/atemio/web/mediathek | grep "$TYPE"_ | tail -n2`
	BFLIST=`ls -1 /var/www/atemio/web/mediathek | grep "$TYPE"_`
	for ROUND1 in $BFLIST; do
		skip=0
		for ROUND2 in $BSLIST; do
			echo [Backup] ROUND1 $ROUND1
			echo [Backup] ROUND2 $ROUND2
			if [ $ROUND1 = $ROUND2 ]; then
				echo [Backup] set skip=1
				skip=1
			fi
			if [ $ROUND1 = ".." ] || [ $ROUND2 = ".." ] || [ $ROUND1 = "." ] || [ $ROUND2 = "." ]; then
				echo [Backup] set skip=1
				skip=1
			fi
		done
		echo [Backup] skip $skip
		if [ $skip = 0 ]; then	
			echo [Backup] start remove user backups
			rm -rf /var/www/atemio/web/mediathek/"$ROUND1"
		fi
	done	
done
