#!/bin/sh

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	sed 's/satipclient=.*//g' -i /mnt/config/start-config
	opkg remove satipclient
	opkg remove titan-plugin-network-satipclient --dest $1
fi

exit 0
