#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1)
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/lcdsamsung" 

if [ -e /tmp/skin.xml_sam ]; then
	mv "$PLUGINDIR/skin.xml" "$PLUGINDIR/skin.xml_org"
	cp /tmp/skin.xml_sam "$PLUGINDIR/skin.xml"
	rm /tmp/skin.xml_sam >/dev/null 2>&1
fi

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-tools-lcdsamsung --dest $1
fi

exit 0
