#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"  
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/lcdsamsung" 

if [ -e "$PLUGINDIR/skin.xml" ]; then
	cp "$PLUGINDIR/skin.xml" /tmp/skin.xml_sam 
fi

rm -rf "$PLUGINDIR"

exit 0