#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1);fi
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/lcdsamsung" 

if [ -e "$PLUGINDIR/skin.xml" ]; then
	cp "$PLUGINDIR/skin.xml" /tmp/skin.xml_sam 
fi

rm -rf "$PLUGINDIR"

exit 0