#!/bin/sh
INSTDIR="$1"  
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/callmonitor1"

if [ -e "$PLUGINDIR/callmon.conf" ]; then
	cp "$PLUGINDIR/callmon.conf" /tmp/callmon.conf 
fi

rm -rf "$PLUGINDIR"

exit 0