#!/bin/sh

echo "Dest: $1"
echo "Script: $0"

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-tools-callmonitor1 --dest $1
fi

if [ "$1" != "upgrade" ];then
	PLUGINDIR="$1/usr/local/share/titan/plugins/callmonitor1"
	echo "PLUGINDIR: $PLUGINDIR"

	if [ ! -e "$PLUGINDIR/callmon.conf" ] && [ -e "$PLUGINDIR/callmon.conf.callmon" ]; then
		echo "use tpk config file: callmon.conf"
		echo "rename $PLUGINDIR/callmon.conf.callmon > $PLUGINDIR/callmon.conf"
		mv "$PLUGINDIR/callmon.conf.callmon" "$PLUGINDIR/callmon.conf"
	else
		echo "found user config file: callmon.conf"
		echo "skip tpk config file: callmon.conf.callmon"
	fi
fi

exit 0
