#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0


if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-tools-callmonitor1 --dest $1
fi

INSTDIR="$1"  
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/callmonitor1"

echo "check callmon.conf"

if [ -e /tmp/callmon.conf ]; then
	echo "restore callmon.conf"
	mv "$PLUGINDIR/callmon.conf" "$PLUGINDIR/callmon.conf_org"
	cp /tmp/callmon.conf "$PLUGINDIR/callmon.conf"
	rm /tmp/callmon.conf
fi

exit 0
