#!/bin/sh

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-tools-callmonitor1 --dest $1
else
	INSTDIR="$1"  
	PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/callmonitor1"

	rm -rf "$PLUGINDIR" >/dev/null 2>&1
fi

exit 0
