#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1);fi
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/callmonitor1"

if [ -e "$PLUGINDIR/callmon.conf" ]; then
	echo "save callmon.conf"
	cp "$PLUGINDIR/callmon.conf" /tmp/callmon.conf 
fi

rm -rf "$PLUGINDIR"

exit 0
