#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"  
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/callmonitor1"

if [ -e "$PLUGINDIR/callmon.conf" ]; then
	echo "save callmon.conf"
	cp "$PLUGINDIR/callmon.conf" /tmp/callmon.conf 
fi

rm -rf "$PLUGINDIR"

exit 0
