#!/bin/sh

echo "Dest: $1"
echo "Script: $0"


if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	sed 's/minisatip=.*//g' -i /mnt/config/start-config
	opkg remove minisatip
	opkg remove titan-plugin-network-minisatip --dest $1
fi

exit 0
