#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1);fi
echo "set INSTDIR $INSTDIR"

if [ "$INSTDIR" == "/var" ]; then
	rm -rf "$INSTDIR/usr/local/share/titan/skin/default"

	echo "restore default skin"
	ln -s /lib/titan/default "$INSTDIR/usr/local/share/titan/skin/default"
	rm -rf "$INSTDIR/etc/titan/skinconfig"
	cp -a /lib/titan/default/skinconfig.default "$INSTDIR/etc/titan/skinconfig"
fi

exit 0