#!/bin/sh

echo "Dest: $1"
echo "Script: $0"


if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-gui-kodistarter --dest $1
	opkg remove kodi
fi

exit 0
