#!/bin/sh
INSTDIR="$1"  
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/wlandisplay" 

if [ -e /tmp/skin.xml_sam ]; then
	mv "$PLUGINDIR/skin.xml" "$PLUGINDIR/skin.xml_org"
	cp /tmp/skin.xml_sam "$PLUGINDIR/skin.xml"
	rm /tmp/skin.xml_sam >/dev/null 2>&1
fi

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg update
	opkg install titan-plugin-tools-wlandisplay --dest $1
fi

exit 0
