#!/bin/sh
INSTDIR="$1"  
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/wlandisplay" 

if [ -e "$PLUGINDIR/skin.xml" ]; then
	cp "$PLUGINDIR/skin.xml" /tmp/skin.xml_sam 
fi

rm -rf "$PLUGINDIR"

exit 0