#!/bin/sh
INSTDIR="$1"

sed s#_path_#"$INSTDIR"#g -i "$INSTDIR/usr/local/share/titan/skin/0Acht5Zehn/skinconfig"
sed s#_path_#"$INSTDIR"#g -i "$INSTDIR/usr/local/share/titan/skin/0Acht5Zehn/skinconfig.default"

exit 0
