#!/bin/sh

echo Use Install Dest: $1
echo Start Install Script: $0

INSTDIR="$1"
if [ "$1" == "upgrade" ];then INSTDIR=$(echo $0 | grep "///" | sed "s!///!\n!g" | head -n1);fi
echo "set INSTDIR $INSTDIR"
PLUGINDIR="$INSTDIR/usr/local/share/titan/plugins/xupnpd"

rm -rf "$PLUGINDIR" >/dev/null 2>&1
rm -rf $INSTDIR/etc/xupnpd >/dev/null 2>&1

if [ ! -e /etc/.opkg ] && ([ -e /etc/.oebuild ] || [ -e /etc/.ovbuild ]);then
	opkg remove titan-plugin-network-xupnpd --dest $1
fi

exit 0
