#!/bin/sh
SVNUSER=$1
SVNPASS=$2
SVNURL=$3

if [ $# -ne 3 ]; then
	echo "|---------------------------------------------------------------------------------------------|"
	echo "|                                                                                             |"
	echo "| Parser Make Script                                                                          |"
	echo "|                                                                                             |"
	echo '| use ./make-parser <svnuser> <svnpass> <svnurl>                                                 |'
	echo "|                                                                                             |"
	echo "| for svnuser <your>                                                                          |"
	echo "| for svnpass <your>                                                                          |"
	echo "| for svnurl <your>                                                                           |"
	echo "|                                                                                             |"
	echo "|---------------------------------------------------------------------------------------------|"
	echo "|                                                                            v2.1@dev-team    |"
	echo "|---------------------------------------------------------------------------------------------|"
	exit 1
fi

HOMEDIR=`pwd`
TMP=.tmp

rm -rf /var/www/atemio/web/mediathek/menu
rm -rf /var/www/atemio/web/mediathek/*.list

rm -rf "$HOME"/flashimg/BUILD/mediathek
svn co --username $SVNUSER --password $SVNPASS http://sbnc.myphotos.cc/svn/titan/titan/tools/tithekmainmenu "$HOME"/flashimg/BUILD/mediathek
svn co --username $SVNUSER --password $SVNPASS http://sbnc.myphotos.cc/svn/titan/skins/tithek/menu "$HOME"/flashimg/BUILD/mediathek/menu
rm -rf `find "$HOME"/flashimg/BUILD/mediathek -type d -name "*.svn"`
mv "$HOME"/flashimg/BUILD/mediathek/* /var/www/atemio/web/mediathek
cd "$HOME"/flashimg/BUILD/mediathek

lasttimestamp=`cat /var/www/atemio/web/mediathek/lasttimestamp`
lasttimestamp=`expr $lasttimestamp + 84500`
today=`date +%s`

if [ $today -gt $lasttimestamp ];then
	ls -1 "$HOME"/flashimg/source.titan/titan/tools/parser/*.sh | sort -r > tmp.txt
else
	ls -1 "$HOME"/flashimg/source.titan/titan/tools/parser/*.sh | grep -v beeg.sh | sort -r > tmp.txt
fi


LINE=`cat tmp.txt`
for TYPE in $LINE; do
	if [ $TYPE == beeg.sh ];then
		echo `date +%s` >/var/www/atemio/web/mediathek/lasttimestamp
	fi

	$TYPE
	echo "[make-parser] make $TYPE"
	STARTTIME=`date +"%Y.%m.%d_%H.%M.%S"`
done

cd "$HOME"/flashimg/BUILD/mediathek/_full
LINE=`ls -1`
TIME=`date +"%Y.%m.%d_%H.%M.%S"`

for TYPE in $LINE; do
	mv $TYPE /var/www/atemio/web/mediathek/"$TYPE"_"$TIME"
	echo "[make-parser]" mv "$TYPE" "> /var/www/atemio/web/mediathek/""$TYPE"_"$TIME"
	rm -rf /var/www/atemio/web/mediathek/"$TYPE"
	echo "[make-parser]" ln -s "$TYPE"_"$TIME" /var/www/atemio/web/mediathek/"$TYPE"
	ln -s "$TYPE"_"$TIME" /var/www/atemio/web/mediathek/"$TYPE"

	BSLIST=`ls -1 /var/www/atemio/web/mediathek | grep "$TYPE"_ | tail -n2`
	BFLIST=`ls -1 /var/www/atemio/web/mediathek | grep "$TYPE"_`
	for ROUND1 in $BFLIST; do
		skip=0
		for ROUND2 in $BSLIST; do
			echo [Backup] ROUND1 $ROUND1
			echo [Backup] ROUND2 $ROUND2
			if [ $ROUND1 = $ROUND2 ]; then
				echo [Backup] set skip=1
				skip=1
			fi
			if [ $ROUND1 = ".." ] || [ $ROUND2 = ".." ] || [ $ROUND1 = "." ] || [ $ROUND2 = "." ]; then
				echo [Backup] set skip=1
				skip=1
			fi
		done
		echo [Backup] skip $skip
		if [ $skip = 0 ]; then	
			echo [Backup] start remove user backups
			rm -r /var/www/atemio/web/mediathek/"$ROUND1"
		fi
	done	
done
